# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include: 
    - main


stages:
  - stage: my_first_stage
    pool: my_hosted_agents
    jobs:
    - job: read_secrets
      displayName: Read Secrets From Vault
      steps:
      - task: VaultReadKV@4
        inputs:
          strUrl: 'http://10.0.1.71:8200'
          ignoreCertificateChecks: true
          useProxy: 'none'
          strNamespaces: '/'
          strAuthType: 'userpass'
          strUsername: 'pipeline'
          strPassword: 'test'
          strKVEnginePath: 'secrets'
          kvVersion: 'v2'
          strSecretPath: 'actions'
          strPrefixType: 'custom'
          strVariablePrefix: 'pipeline'
          replaceCR: false
      - script: |
          echo $(pipeline_username) > /tmp/my_secrets
          echo $(pipeline_password) >> /tmp/my_secrets
        displayName: write secrets to file /tmp/my_secrets
      # - script: env > /tmp/pipeline_env
  - stage: my_second_stage
    displayName: Use Consumed Vault Secrets 
    dependsOn: my_first_stage
    pool: my_hosted_agents
    jobs:
      - job: write_secrets_to_file
        displayName: Write Stage One Secrets to /tmp/stage_2_secrets
        steps:
          - script: |
              echo $(pipeline_username) > /tmp/stage_2_secrets
              echo $(pipeline_password) >> /tmp/stage_2_secrets
            displayName: 2nd stage write to file 
          

# trigger:
# - main

# pool: my_hosted_agents
#   # vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
